Sp2 86 create asset manager class
SDU-Semester-Project-2/Heatington pull request #19
Opened 2024-04-07 19:44 UTC by magwrap

# Asking for review | NOT TESTED

I think basic functionallity is done. Tests are still not ready! But if you need this class for further work feel free to emergency merge into dev or your local branch(may result in conflicts).

 - provides data about production units and heating grid
 - multiple overloaded ways for writing (editing) production unit 
 - JsonController does basic Seriallization, Deserializaton, readdata and writedata implementing IReadWriteController and IDeserializeSerialize
 - also implemented JsonDataSource (followed the convension followed in #12) but for me using JsonController makes more sense so JsonDataSource is unused.

 
 _Question_:
 Isin't the name HeatingUnit kinda confusing? It implies existance of other sub-group of units in ProductionUnits but in reality they are the same.

2024-04-08 10:30 UTC, pkyeager requested changes
Good job, if tested(simple console.log, checking if units get instantiated, access is working and etc.) or directly a unit test. 

Are more md files for documentation in coming?

2024-04-08 10:34 UTC, pkyeager commented
> _Question_: Isin't the name HeatingUnit kinda confusing? It implies existance of other sub-group of units in ProductionUnits but in reality they are the same.

I think, this is a legit question.

2024-04-08 11:08 UTC, magwrap commented
> Good job, if tested(simple console.log, checking if units get instantiated, access is working and etc.) or directly a unit test.
> 
> Are more md files for documentation in coming?

Yes of course documentation is coming too, I did the logs in my project but deleted them so not to pollute the code.

2024-04-08 11:57 UTC, KonyakB requested changes
seems good beside the typo

2024-04-08 11:57 UTC, KonyakB commented on Heatington/Controllers/JsonController.cs
> +public class ProductionUintJsonConverter : JsonConverter<ProductionUnit>
```suggestion
public class ProductionUnitJsonConverter : JsonConverter<ProductionUnit>
```
there is a typo here ("ProductionUint...")

2024-04-09 05:11 UTC, pkyeager approved these changes

2024-04-09 10:52 UTC, frske approved these changes
LGTM

2024-04-09 11:41 UTC, KonyakB approved these changes

2024-04-09 11:41 UTC, merged