Sp2 91 create csv controller class
SDU-Semester-Project-2/Heatington pull request #25
Opened 2024-04-10 09:12 UTC by 0rangeBlaze

I have added the documentation for the CsvSerializer. Please check if it is understandable and there are no typos or any other issue.

2024-04-11 05:29 UTC, pkyeager commented on Documentation/Heatington/Controllers/Serializers/CsvController.md
> +### Create\<T\>
I may be wrong, but I do believe this format is better for readabilty. 
```suggestion
### Create\<T\>

`public static CsvData Create<T>(List<T> data, string[]? header = null)`

Parameters:

- `data` (List<T>): this is a list of objects that you want to represent as CSV data. 
- `header` (string[]?, optional): a default header to be used. Default is null.

Returns:

- CsvData: Returns the `CsvData` created from `data` and `header`.
```

2024-04-11 05:34 UTC, pkyeager commented on Documentation/Heatington/Controllers/Serializers/CsvController.md
> +If header is null a header is created from the list of public properties of the T type. The CSV data will contain the values of the public properties of the T type turned to string via .ToString(), i
I may be wrong, but I do believe this format is better for readabilty. The same is for another methods in this documentation.
```suggestion
### Create\<T\>

`public static CsvData Create<T>(List<T> data, string[]? header = null)`

Parameters:

- `data` (List<T>): this is a list of objects that you want to represent as CSV data. 
- `header` (string[]?, optional): a default header to be used. Default is null.

Returns:

- CsvData: Returns the `CsvData` created from `data` and `header`.
```

```

2024-04-12 19:29 UTC, magwrap commented
rebased new changes

2024-04-13 10:52 UTC, frske approved these changes
Nothing more to review here. This PR can be closed imo

2024-04-13 11:18 UTC, magwrap requested changes
Emm now all the documentation is held in docs/ directory. 
- Move the CsvController.md from Documentation/Heatington/Controllers/ to docs/Heatingtion/Services/CsvSerializer.md
The document is only for serializer not csv controller right? So the name should match.

Sorry Dani :(

2024-04-14 11:31 UTC, magwrap approved these changes
All good

2024-04-14 11:31 UTC, merged